/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package studentdata;
import app.db.Student;
import app.db.StudentManager;
import java.util.ArrayList; 
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Rifqi Adam
 */
public class MainWindow extends javax.swing.JFrame {
    List<Student> students = new ArrayList<>();
    int currentRow = 0;
    
    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        String lookAndFeel =
        javax.swing.UIManager.getSystemLookAndFeelClassName(); 
        try {
            javax.swing.UIManager.setLookAndFeel(lookAndFeel);
        }catch (ClassNotFoundException | IllegalAccessException | InstantiationException | UnsupportedLookAndFeelException e){            
        }
            initComponents();
            loadData(); 
            bindData();
            this.setTitle("Data Mahasiswa"); 
            txtNim.setEditable(false); 
            txtNama.setEditable(false); 
            txtAlamat.setEditable(false); 
            txtEmail.setEditable(false);
            this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNim = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAlamat = new javax.swing.JTextArea();
        btnPrev = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnNew = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("DataMahasiswa"));

        jLabel1.setText("NIM");

        jLabel2.setText("Nama");

        jLabel3.setText("Alamat");

        jLabel4.setText("Email");

        txtAlamat.setColumns(20);
        txtAlamat.setRows(5);
        jScrollPane1.setViewportView(txtAlamat);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNim)
                    .addComponent(txtEmail)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtNama))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 51, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        btnPrev.setText("<<");
        btnPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevActionPerformed(evt);
            }
        });

        btnNext.setText(">>");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnNew.setText("Tambah baru");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnDelete.setText("Hapus");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnPrev)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNext)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                        .addComponent(btnNew)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEdit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDelete)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPrev)
                    .addComponent(btnNext)
                    .addComponent(btnNew)
                    .addComponent(btnEdit)
                    .addComponent(btnDelete))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        if (btnNew.getText().equals("Tambah baru")) {
            txtNim.setText("");
            txtNama.setText("");
            txtAlamat.setText(""); 
            txtEmail.setText("");
            txtNim.setEditable(true); 
            txtNama.setEditable(true); 
            txtAlamat.setEditable(true); 
            txtEmail.setEditable(true); 
            txtNim.requestFocus(); 
            btnNew.setText("Simpan"); 
            btnDelete.setText("Batal"); 
            btnEdit.setEnabled(false); 
            btnPrev.setEnabled(false); 
            btnNext.setEnabled(false);
        } else {
            if (txtNama.getText().equals("") || txtNim.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Mohon isi datadengan benar", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            } else{
                StudentManager studentmgr = new StudentManager(); //buka koneksi
                Student s = new Student();
                s.setNim(txtNim.getText());
                s.setName(txtNama.getText());
                s.setAddress(txtAlamat.getText()); 
                s.setEmail(txtEmail.getText());
                if (studentmgr.Insert(s) > 0){
                    loadData();
                    currentRow = students.size() - 1;
                    bindData();
                    JOptionPane.showMessageDialog(this, "Data berhasil disimpan", "Informasi", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this, "Data gagal disimpan","Informasi", JOptionPane.INFORMATION_MESSAGE);
                }
                txtNim.setEditable(false);
                txtNama.setEditable(false);
                txtAlamat.setEditable(false);
                txtEmail.setEditable(false);
                btnNew.setText("Tambah baru");
                btnDelete.setText("Hapus");
                btnEdit.setEnabled(true);
                btnPrev.setEnabled(true);
                btnNext.setEnabled(true); 
                studentmgr.closeConnection(); //tutup koneksi
            }
        }
    }//GEN-LAST:event_btnNewActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
         if (btnEdit.getText().equals("Edit")) {
            txtNim.setEditable(true);
            txtNama.setEditable(true); 
            txtAlamat.setEditable(true); 
            txtEmail.setEditable(true); 
            btnEdit.setText("Simpan"); 
            btnDelete.setText("Batal"); 
            btnNew.setEnabled(false); 
            btnPrev.setEnabled(false); 
            btnNext.setEnabled(false);
        } else {
            StudentManager studentmgr = new StudentManager();
            Student s = students.get(currentRow); 
            s.setNim(txtNim.getText());
            s.setName(txtNama.getText()); 
            s.setAddress(txtAlamat.getText()); 
            s.setEmail(txtEmail.getText());
            if (studentmgr.Update(s) > 0) {
                loadData();
                bindData(); 
                JOptionPane.showMessageDialog(this, "Data berhasil diupdate", "Information", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Data gagal diupdate", "Information", JOptionPane.INFORMATION_MESSAGE);
            }
            txtNim.setEditable(false); 
            txtNama.setEditable(false); 
            txtAlamat.setEditable(false); 
            txtEmail.setEditable(false); 
            btnEdit.setText("Edit"); 
            btnDelete.setText("Hapus"); 
            btnNew.setEnabled(true); 
            btnPrev.setEnabled(true); 
            btnNext.setEnabled(true);
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        if (btnDelete.getText().equals("Hapus")) {
            int dialog = JOptionPane.showConfirmDialog(this,"Apakah Anda yakin akan menghapus data ini?","Konfirmasi", JOptionPane.YES_NO_OPTION); 
            StudentManager studentmgr = new StudentManager(); //buka koneksi
            Student s = students.get(currentRow); 
            if(dialog == JOptionPane.YES_OPTION){ 
            if (studentmgr.Delete(s) > 0) {
                loadData();
                currentRow = currentRow - 1; 
                bindData();
                JOptionPane.showMessageDialog(this, "Data berhasil dihapus","Informasi", JOptionPane.INFORMATION_MESSAGE);
            }else {
                JOptionPane.showMessageDialog(this, "Data gagal dihapus", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            }
            studentmgr.closeConnection(); //tutup koneksi
            }
            } else if (btnDelete.getText().equals("Batal")) { 
                loadData();
                bindData();
                btnNew.setText("Baru"); 
                btnEdit.setText("Edit"); 
                btnDelete.setText("Hapus"); 
                btnEdit.setEnabled(true); 
                btnNew.setEnabled(true); 
                btnPrev.setEnabled(true); 
                btnNext.setEnabled(true); 
                txtNim.setEditable(false); 
                txtNama.setEditable(false); 
                txtAlamat.setEditable(false); 
                txtEmail.setEditable(false);
            }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
         if(currentRow < students.size() - 1) {
            ++currentRow;
            btnPrev.setEnabled(true);
        } else {
            btnNext.setEnabled(false);
        }
        bindData();
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevActionPerformed
        if(currentRow > 0) {
            --currentRow;
            btnNext.setEnabled(true);
        } else {
            btnPrev.setEnabled(false);
        }
        bindData();
    }//GEN-LAST:event_btnPrevActionPerformed

    private void loadData() {
        StudentManager studentmgr = new StudentManager(); 
        students = studentmgr.getStudents(); 
        studentmgr.closeConnection();
    }
    private void bindData() {
        if (students.size() > 0) {
            Student s = students.get(currentRow); 
            txtNim.setText(s.getNim()); 
            txtNama.setText(s.getName()); 
            txtAlamat.setText(s.getAddress()); 
            txtEmail.setText(s.getEmail());
        } else {
            currentRow = 0;
            txtNim.setText(""); 
            txtNama.setText("");
            txtAlamat.setText(""); 
            txtEmail.setText("");
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MainWindow().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrev;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtAlamat;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNim;
    // End of variables declaration//GEN-END:variables
}
